name: pretest

on:
  push:
    branches:
      - main

jobs:
  build-cdn:
    name: Build CDN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish cdn docker images
      run: make docker-push

  deploy:
    name: Deploy CDN
    needs: [ build-cdn ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 murmprod

    - name: Restart CDN deployment
      run: make deploy
